services:
  nginx:
    build: ./nginx
    image: dnd-assist-nginx:latest
    container_name: nginx
    networks:
      - gateway
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  psql:
    container_name: psql
    build: ./psql
    image: dnd-assist-psql:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /usr/dnd-assist/db-init:/docker-entrypoint-initdb.d
      - /usr/dnd-assist/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - gateway
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  django:
    build: ./django
    image: dnd-assist-django:latest
    container_name: django
    networks:
      - gateway
    ports:
      - "${DJANGO_PORT}:8000"
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=dnd-assist.settings
    depends_on:
      - redis
      - psql
      
networks:
  gateway: {}
