# Generated by Django 4.1.13 on 2024-10-23 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('global_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='my_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
                ('intelligence', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='my_app.character')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_status', models.CharField(max_length=50)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('rooms_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='my_app.roomslist')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFigures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture_id', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_figures', to='my_app.table')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='my_app.room'),
        ),
        migrations.CreateModel(
            name='EntityFigures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_id', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_figures', to='my_app.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_figures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dice_type', models.CharField(max_length=50)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='my_app.table')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='my_app.game')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='my_app.room')),
            ],
        ),
    ]
